path: /Users/aagam/Downloads/IPD/Final Model/data
train: images/train
val: images/val
nc: 8
names: ['damaged door', 'damaged window', 'damaged headlight', 'damaged mirror', 'dent', 'damaged hood', 'damaged bumper', 'damaged wind shield']